#!/bin/bash

# FeishuMind GitHub 仓库配置脚本

echo "==================================="
echo "FeishuMind GitHub 配置助手"
echo "==================================="
echo ""

# 仓库信息
REPO="iqvpi1024/feishumind"
REPO_URL="https://github.com/$REPO"

echo "📋 仓库配置清单："
echo ""
echo "1️⃣  仓库基本信息"
echo "   描述: 开源的、半自主 AI 职场参谋，专为飞书生态设计"
echo "   Website: https://github.com/iqvpi1024/feishumind#readme"
echo ""
echo "2️⃣  Topics（标签）- 需要手动添加："
echo "   ai-agent, feishu, langchain, fastapi, python,"
echo "   llm, memory, automation, workplace, chatbot, productivity"
echo ""
echo "3️⃣  功能开关 - 需要手动启用："
echo "   ✅ Issues"
echo "   ✅ Projects"
echo "   ✅ Discussions"
echo "   ✅ Actions"
echo "   ✅ Security & analysis > Dependabot"
echo ""
echo "==================================="
echo ""
echo "🚀 快速链接："
echo ""
echo "📝 修改仓库设置："
echo "   $REPO_URL/settings"
echo ""
echo "🏷️  添加 Topics："
echo "   $REPO_URL/settings"
echo "   （向下滚动到 Topics 部分）"
echo ""
echo "⚙️  配置功能开关："
echo "   $REPO_URL/settings"
echo "   （在左侧菜单中找到各功能开关）"
echo ""
echo "🔒 设置分支保护："
echo "   $REPO_URL/settings/branches"
echo ""
echo "👥 创建项目看板："
echo "   $REPO_URL/projects"
echo ""
echo "📢 创建 Release："
echo "   $REPO_URL/releases/new?tag=v1.0.0"
echo ""
echo "==================================="
echo ""
echo "✅ 已完成："
echo "   - Tag v1.0.0 已创建并推送"
echo "   - 代码已全部提交并推送"
echo "   - 文档已完善"
echo "   - CI/CD 已配置"
echo ""
echo "🎯 待完成（需要手动操作）："
echo "   1. 创建 Release（见上方链接）"
echo "   2. 添加 Topics 标签"
echo "   3. 配置仓库描述"
echo "   4. 启用功能开关"
echo "   5. 设置分支保护（可选）"
echo ""
echo "==================================="
echo ""
echo "📖 详细配置指南请查看: .github/FINISH_RELEASE.md"
echo ""
